apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: kustom-

resources:
  - api-test-deployment.yaml 
  - stateful-postgres.yaml 

patchesStrategicMerge:
  - patch.yaml

vars:
  - name: POSTGRESS_SERVICE
    objref:
      kind: Service
      name: pg-db 
      apiVersion: v1
